version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      root-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: monthly
    groups:
      web-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
